//php include 'rpcdef' 
var LogServiceService;
(function (LogServiceService) {
    var Debug = (function () {
        function Debug() {
        }
        Debug.prototype.clear = function () {
            return file_put_contents('log.txt', '');
        };
        Debug.prototype.write = function (value) {
            return file_put_contents('log.txt', value, FILE_APPEND);
        };
        return Debug;
    }());
    LogServiceService.Debug = Debug;
})(LogServiceService || (LogServiceService = {}));
//---AUTOGENERATED CODE BELOW: typescript dispatcher for php, please do not modify any code blow 
include('phputil.php');
var postInput = file_get_contents("php://input");
var jsonObject = json_decode(postInput);
switch (jsonObject.service) {
    case 'Debug':
        var LogService_Debug = new LogServiceService.Debug();
        switch (jsonObject.method) {
            case 'clear':
                var LogService_Debug_clearResult = LogService_Debug.clear();
                echo(json_encode(LogService_Debug_clearResult));
                break;
            case 'write':
                var LogService_Debug_write_parameter_0 = jsonObject.parameters[0];
                var LogService_Debug_writeResult = LogService_Debug.write(LogService_Debug_write_parameter_0);
                echo(json_encode(LogService_Debug_writeResult));
                break;
        }
        break;
}
//# sourceMappingURL=LogService.js.map